### ISSUE TITLE
Error getting EF 7.0.0-rc1-final to work 

### ISSUE THREAD

**Issue by supadrasta** [aspnet/DependencyInjection#436]
1) I am getting the following error on the below code when trying to get EF 7 7.0.0-rc1-final to work.
 services.AddEntityFramework()
                .AddDbContext<SampleDBContext>(options =>
            {
               options.UseSqlServer(Configuration.GetSection("Data:ConnectionString").Value);
           });

The error I get is:
System.TypeLoadException was unhandled by user code
'Microsoft.Extensions.DependencyInjection.ServiceCollectionExtensions' from assembly Microsoft.Extensions.DependencyInjection.Abstractions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60.
  Source=EntityFramework.Core
  TypeName=Microsoft.Extensions.DependencyInjection.ServiceCollectionExtensions
  StackTrace:
       at Microsoft.Extensions.DependencyInjection.EntityFrameworkServiceCollectionExtensions.AddEntityFramework(IServiceCollection serviceCollection)
       at SampleWeb.Startup.ConfigureServices(IServiceCollection services)
  InnerException: 

here is my project.json

{
  "buildOptions": {
    "emitEntryPoint": true,
    "preserveCompilationContext": true
  },
  "dependencies": {
    "EntityFramework.Core": "7.0.0-rc1-final",
    "EntityFramework.MicrosoftSqlServer": "7.0.0-rc1-final",
    "EntityFramework.Relational": "7.0.0-rc1-final",
    "EntityFramework.Commands": "7.0.0-rc1-final",
    "Microsoft.AspNetCore.Diagnostics":  "1.0.0",
    "Microsoft.AspNetCore.Mvc":  "1.0.0",
    "Microsoft.AspNetCore.Razor.Tools": {
      "version": "1.0.0-preview2-final",
      "type": "build"
    },
    "Microsoft.AspNetCore.Server.IISIntegration": "1.0.0",
    "Microsoft.AspNetCore.Server.Kestrel": "1.0.0",
    "Microsoft.AspNetCore.StaticFiles": "1.0.0",
    "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.0.0",
    "Microsoft.Extensions.Configuration.Json": "1.0.0",
    "Microsoft.Extensions.DependencyInjection": "1.0.0",
    "Microsoft.Extensions.DependencyInjection.Abstractions": "1.0.0",
    
    "Microsoft.Extensions.Configuration.UserSecrets":  "1.0.0",
    "Microsoft.Extensions.Logging": "1.0.0",
    "Microsoft.Extensions.Logging.Console": "1.0.0",
    "Microsoft.Extensions.Logging.Debug":  "1.0.0",
   
    "Microsoft.Extensions.Options.ConfigurationExtensions": "1.0.0",
    "Microsoft.NETCore.App": {
      "version": "1.0.0",
      "type": "platform"
    },
    "Microsoft.VisualStudio.Web.BrowserLink.Loader": "14.0.0"
  },
  "frameworks": {
    "netcoreapp1.0": {
      "imports": [
        "dotnet5.6",
        "portable-net451+win8",
        "portable-net45+win8+dnxcore50",
        "portable-net45+win8+wp8",
        "portable-net45+win8",
        "dnxcore50",
        "netcore50",
        "netcoreapp-1.0"
      ]
    }
  },
  "commands": { "ef": "EntityFramework.Commands", "web": "Microsoft.AspnetCore.Server.Kestrel"},

  "publishOptions": {
    "include": [
      "wwwroot",
      "Views",
      "Areas/**/Views",
      "appsettings.json",
      "web.config"
    ]
  },
  "runtimeOptions": {
    "configProperties": {
      "System.GC.Server": true
    }
  },
  "scripts": {
    "prepublish": [ "bower install", "dotnet bundle" ],
    "postpublish": [ "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%" ]
  },
  "tools": {
    "BundlerMinifier.Core": "2.0.238",
    "Microsoft.AspNetCore.Razor.Tools": "1.0.0-preview2-final",
    "Microsoft.AspNetCore.Server.IISIntegration.Tools": "1.0.0-preview2-final",
    "Microsoft.EntityFrameworkCore.Tools": {
      "version": "1.0.0-preview1-final",
      "imports": [
        "portable-net45+win8+dnxcore50",
        "portable-net45+win8"
      ]
    }
  }
  }

**Comment by supadrasta** [comment]
Pranav, I installed these packages in place of rc1 equivalents. Now DbSet<> and DbContext fail references. As per documentation they are part of : Microsoft.EntityFrameworkCore 1.0.0
