### ISSUE TITLE
Inconsistent handling of internal types vs public constructors

### ISSUE THREAD

**Issue by Tratcher** [aspnet/DependencyInjection#441]
DI allows you to register internal types, but requires the constructors to be public. Why not allow internal constructors as well?

```
[12:52:37][xunit-test]       Unhandled Exception: System.InvalidOperationException: A suitable constructor for type 'Microsoft.AspNetCore.Server.WebListener.MessagePump' could not be located. Ensure the type is concrete and services are registered for all parameters of a public constructor.
[12:52:37][xunit-test]          at Microsoft.Extensions.DependencyInjection.ServiceLookup.Service.CreateCallSite(ServiceProvider provider, ISet`1 callSiteChain)
[12:52:37][xunit-test]          at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetResolveCallSite(IService service, ISet`1 callSiteChain)
[12:52:37][xunit-test]          at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetServiceCallSite(Type serviceType, ISet`1 callSiteChain)
[12:52:37][xunit-test]          at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(Type serviceType, ServiceProvider serviceProvider)
[12:52:37][xunit-test]          at System.Collections.Concurrent.ConcurrentDictionaryExtensions.GetOrAdd[TKey,TValue,TArg](ConcurrentDictionary`2 dictionary, TKey key, Func`3 valueFactory, TArg arg)
[12:52:37][xunit-test]          at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
[12:52:37][xunit-test]          at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
[12:52:37][xunit-test]          at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
[12:52:37][xunit-test]          at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureServer()
[12:52:37][xunit-test]          at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
[12:52:37][xunit-test]          at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
[12:52:37][xunit-test]          at ServerComparison.TestSites.Program.Main(String[] args)
```

For some reason InternalsVisableTo bypasses this issue.

**Comment by Eilon** [comment]
Internal constructors often exist for non-DI purposes, and if we allow including them, it would likely mess up the default container's resolution logic. This would likely be a huge compat break for perhaps very little value...

**Comment by Tratcher** [comment]
You you accept internal types?

**Comment by Tratcher** [comment]
It's worth noting that in this example there is only one constructor, there is no ambiguity.

**Comment by khellang** [comment]
Why can't the internal type have a public ctor? :wink:

**Comment by khellang** [comment]
Anyway, this will probably break all existing adapters.

BTW, is there specification tests ensuring that adapters don't pick internal ctors?

I know we already have to do custom ctor selection in StructureMap because it doesn't consider registered services when picking a ctor by default.

**Comment by Eilon** [comment]
Supporting internal types is somewhat questionable as well. But it's not terribly harmful because the *type* registration is always explicit (with the built-in container), so surely "you know what you're doing." 😄
