### ISSUE TITLE
Support for IReadOnlyList<T> as a dependency

### ISSUE THREAD

**Issue by Kralizek** [aspnet/DependencyInjection#512]
As of now, `IReadOnlyList<T>` is not recognized as a valid dependency.

Dependencies:
```csharp
public interface IDependency{}

public class DependencyA : IDependency {}

public class DependencyB : IDependency {}
```

Dependent code:
```csharp
public class EnumerableDependent 
{
    public EnumerableDependent (IEnumerable<IDependency> dependencies)
    {
        if (dependencies is null) throw new ArgumentNullException(nameof(dependencies));

        Dependencies = dependencies.ToArray();
    }

    public IReadOnlyList<IDependency> Dependencies { get; }
}

public class ReadOnlyListDependent 
{
    public ReadOnlyListDependent (IReadOnlyList<IDependency> dependencies)
    {
        if (dependencies is null) throw new ArgumentNullException(nameof(dependencies));

        Dependencies = dependencies.ToArray();
    }

    public IReadOnlyList<IDependency> Dependencies { get; }
}
```

Test code
```csharp
class Program
{
    static void Main(string[] args)
    {
        IServiceCollection services = new ServiceCollection();
        services.AddSingleton<IDependency, DependencyB>();
        services.AddSingleton<IDependency, DependencyA>();

        services.AddSingleton<EnumerableDependent>();
        services.AddSingleton<ReadOnlyListDependent>();

        var sp = services.BuildServiceProvider();

        TryResolve<EnumerableDependent>(sp);
        TryResolve<ReadOnlyListDependent>(sp);
    }

    static void TryResolve<T>(IServiceProvider serviceProvider)
    {
        try{
            var item = serviceProvider.GetRequiredService<T>();

            System.Console.WriteLine($"OK: {typeof(T).FullName}");
        }
        catch (Exception ex)
        {
            System.Console.WriteLine($"Nope: {typeof(T).FullName}");
        }

    }
}
```

Output
```
OK: test_deps.EnumerableDependent
Nope: test_deps.ReadOnlyListDependent
```

Exception
```
System.InvalidOperationException: Unable to resolve service for type 'System.Collections.Generic.IReadOnlyList`1[test_deps.IDependency]' while attempting to activate 'test_deps.ReadOnlyListDependent'.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.Service.PopulateCallSites(ServiceProvider provider, ISet`1 callSiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.Service.CreateCallSite(ServiceProvider provider, ISet`1 callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetResolveCallSite(IService service, ISet`1 callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetServiceCallSite(Type serviceType, ISet`1 callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(Type serviceType, ServiceProvider serviceProvider)
   at System.Collections.Concurrent.ConcurrentDictionaryExtensions.GetOrAdd[TKey,TValue,TArg](ConcurrentDictionary`2 dictionary, TKey key, Func`3 valueFactory, TArg arg)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at test_deps.Program.TryResolve[T](IServiceProvider serviceProvider) in C:\Users\MyUser\Desktop\test-deps\Program.cs:line 27
```

Expected result: the dependency is served via any collection implementing `IReadOnlyList<T>` (e.g. `T[]` or `List<T>`)

[test-deps.zip](https://github.com/aspnet/DependencyInjection/files/919059/test-deps.zip)

**Comment by davidfowl** [comment]
We're not adding any features that aren't supported by at least the critical mass of other mainstream containers. What other containers support `IReadOnlyList<T>`? Using `IEnumerable<T>` is the work around.

**Comment by Kralizek** [comment]
Castle Windsor does it. Not sure about other containers because my team focuses mostly onto CW.

I know that `IEnumerable<T>` is a valid workaround, but the semantic it carries is totally different from the one behind `IReadOnlyList<T>`.

**Comment by muratg** [comment]
We don't plan to do this.
