### ISSUE TITLE
Unable to resolve service for type 'Microsoft.AspNetCore.Cors.Infrastructure.ICorsService' 

### ISSUE THREAD

**Issue by dynamiclynk** [aspnet/DependencyInjection#525]
```
Application startup exception: System.InvalidOperationException: Unable to resolve service for type 'Microsoft.AspNetCore.Cors.Infrastructure.ICorsService' while attempting to activate 'Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware'.
   at Microsoft.Extensions.Internal.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass3_0.<UseMiddleware>b__0(RequestDelegate next)
   at Microsoft.AspNetCore.Builder.Internal.ApplicationBuilder.Build()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
crit: Microsoft.AspNetCore.Hosting.Internal.WebHost[6]
```

I get this stdout log after updating to VS2017 and nuget packages 1.1.2 StartUp > ConfigureServices, and Configure but have AddCors and UseCore respectively.

Csproj contains the reference `<PackageReference Include="Microsoft.AspNetCore.Cors" Version="1.1.2" />`

**Comment by bizmonger** [comment]
I have the same issue. Any suggestions on how to resolve this?
